import{useEffect,useMemo,useState}from'react';
import{signOut,type User}from'firebase/auth';
import{BookOpen,Check,History,LogOut,Plane,RotateCcw,Search,Users,X}from'lucide-react';
import{auth}from'./firebase';
import{awardMiles,undoReward,watchRewards,watchStudents}from'./services';
import{rewardConfig,type Reward,type RewardType,type Student}from'./types';

export default function Dashboard({user}:{user:User}){
 const[students,setStudents]=useState<Student[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[pending,setPending]=useState<{student:Student;type:RewardType}|null>(null),[historyStudent,setHistoryStudent]=useState<Student|null>(null),[rewards,setRewards]=useState<Reward[]>([]),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[success,setSuccess]=useState('');
 useEffect(()=>watchStudents(setStudents,setError),[]);
 useEffect(()=>historyStudent?watchRewards(historyStudent.uid,setRewards,setError):undefined,[historyStudent]);
 const filtered=useMemo(()=>students.filter(s=>(s.displayName+' '+s.username).toLowerCase().includes(query.toLowerCase())),[students,query]);
 async function confirm(){if(!pending)return;try{setBusy(true);await awardMiles(pending.student,pending.type,note);setSuccess(`${rewardConfig[pending.type].label} added to ${pending.student.displayName}.`);setPending(null);setNote('');setTimeout(()=>setSuccess(''),3000)}catch(e){setError(e instanceof Error?e.message:'Could not add miles.')}finally{setBusy(false)}}
 async function reverse(reward:Reward){if(!historyStudent||!window.confirm(`Undo ${rewardConfig[reward.type]?.label??'this award'} +${reward.miles}?`))return;try{setBusy(true);await undoReward(historyStudent,reward);setSuccess('Award was undone.');setTimeout(()=>setSuccess(''),3000)}catch(e){setError(e instanceof Error?e.message:'Could not undo award.')}finally{setBusy(false)}}
 return <div className="dashboard"><header><div className="logo"><Plane/><span><b>Journey Control</b><small>ADMIN DASHBOARD</small></span></div><div className="admin-user"><span>{user.email?.[0].toUpperCase()}</span><div><small>SIGNED IN AS</small><b>{user.email}</b></div><button onClick={()=>signOut(auth)} title="Sign out"><LogOut/></button></div></header><main><div className="welcome"><div><small>STUDENT PROGRESS</small><h1>Journeys at a glance</h1><p>Award Journey Miles and keep every explorer moving.</p></div><aside><Users/><span><strong>{students.length}</strong><small>Students</small></span></aside></div>{success&&<div className="success"><Check/>{success}</div>}{error&&<div className="error banner"><span>{error}</span><button onClick={()=>setError('')}><X/></button></div>}<div className="toolbar"><div><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search students..."/></div></div><section className="table-card"><table><thead><tr><th>STUDENT</th><th>JOURNEY MILES</th><th>HISTORY</th><th>HOMEWORK</th><th>WORDS</th><th>CREATIVE</th><th>BONUS</th></tr></thead><tbody>{filtered.map(s=><tr key={s.uid}><td><span className="avatar">{s.displayName[0]}</span><div><b>{s.displayName}</b><small>@{s.username}</small></div></td><td><strong className="miles">{s.journeyMiles}</strong></td><td><button className="history-btn" onClick={()=>setHistoryStudent(s)}><History/>View</button></td>{(Object.keys(rewardConfig)as RewardType[]).map(type=><td key={type}><button className={`award ${rewardConfig[type].color}`} onClick={()=>setPending({student:s,type})}>+{rewardConfig[type].miles}<span>{rewardConfig[type].label}</span></button></td>)}</tr>)}</tbody></table>{filtered.length===0&&<div className="empty"><BookOpen/><p>No students found.</p></div>}</section></main>
 {pending&&<div className="modal-backdrop" onMouseDown={()=>setPending(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setPending(null)}><X/></button><small>CONFIRM REWARD</small><h2>{rewardConfig[pending.type].label} +{rewardConfig[pending.type].miles}</h2><p>Add to <b>{pending.student.displayName}</b>? Their total will change from {pending.student.journeyMiles} to {pending.student.journeyMiles+rewardConfig[pending.type].miles} Journey Miles.</p><label>NOTE (OPTIONAL)<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="A short note for the journey log"/></label><button className="confirm" onClick={confirm} disabled={busy}>{busy?'Adding...':'Confirm award'}</button></div></div>}
 {historyStudent&&<div className="modal-backdrop" onMouseDown={()=>setHistoryStudent(null)}><div className="history-panel" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setHistoryStudent(null)}><X/></button><small>JOURNEY HISTORY</small><h2>{historyStudent.displayName}</h2><p>{historyStudent.journeyMiles} Journey Miles</p><div className="reward-list">{rewards.map(r=><article key={r.id}><i className={rewardConfig[r.type]?.color}>{rewardConfig[r.type]?.label?.[0]??'?'}</i><div><b>{rewardConfig[r.type]?.label??r.type}</b><small>{r.lessonDate?.toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})??'Date pending'}</small>{r.note&&<p>{r.note}</p>}</div><strong>+{r.miles}</strong>{r.source==='admin-app'?<button onClick={()=>reverse(r)} disabled={busy} title="Undo award"><RotateCcw/></button>:<span className="manual">Manual</span>}</article>)}{rewards.length===0&&<div className="empty"><p>No journey entries yet.</p></div>}</div></div></div>}
 </div>
}
